export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SET_FEE_INSTALLMENTS = "SET_FEE_INSTALLMENTS";
export const SET_YEAR = "SET_YEAR";
export const SET_FEE_TYPE = "SET_FEE_TYPE";
export const SET_CLASSES = "SET_CLASSES";
export const SET_DISTINCT_CLASSES = "SET_DISTINCT_CLASSES";
export const SET_CLASS_PERIOD = "SET_CLASS_PERIOD";
export const SET_SUBJECTS = "SET_SUBJECTS";
export const SET_TEACHERS = "SET_TEACHERS";
export const SET_TIMETABLE = "SET_TIMETABLE";
export const SET_TIMETABLE_TEACHER = "SET_TIMETABLE_TEACHER";
export const ASSIGNED_CLASS = "ASSIGNED_CLASS";
export const SET_CLASS_HOMEWORK = "SET_CLASS_HOMEWORK";
export const SET_TEACHER_HOMEWORK = "SET_TEACHER_HOMEWORK";
export const SET_TEACHER_PAST_HOMEWORK = "SET_TEACHER_PAST_HOMEWORK";
export const SET_TEACHER_ONLINEXAM = "SET_TEACHER_ONLINEXAM"

export const SET_STUDENT_CURRENT_HOMEWORK = "SET_STUDENT_CURRENT_HOMEWORK";
export const SET_STUDENT_PAST_HOMEWORK = "SET_STUDENT_PAST_HOMEWORK";



export const SET_PARENT_CHILDS = "SET_PARENT_CHILDS";
export const SET_PARENT_HOMEWORK = "SET_PARENT_HOMEWORK";
export const SET_CLASSWISE_TIMETABLE = "SET_CLASSWISE_TIMETABLE";
export const SET_EXAM_TYPE = "SET_EXAM_TYPE";
export const SET_TEACHERS_NAME = "SET_TEACHERS_NAME";
export const ADMIN_STUDENT_HEADER = "ADMIN_STUDENT_HEADER"
export const SCHOOL_CLERKS = "SCHOOL_CLERKS"
export const SET_MONTHLY_TEST = "SET_MONTHLY_TEST"
export const SET_STUDY_MATERIAL_GROUPS = "SET_STUDY_MATERIAL_GROUPS"
export const SET_CLASSWISE_SUBJECTS = "SET_CLASSWISE_SUBJECTS"
export const SET_QUESTION_PAPER = "SET_QUESTION_PAPER"
export const SET_CLASSWISE_MONTHLYTEST = "SET_CLASSWISE_MONTHLYTEST"
export const SET_ONLINE_CLASSWISE_MONTHLYTEST = "SET_CLASSWISE_ONLINE_MONTHLYTEST"
export const SET_TEACHER_STUDY_MATERIAL_GROUPS = "SET_TEACHER_STUDY_MATERIAL_GROUPS"
export const SET_MONTHLYTEST_RESULT = "SET_MONTHLYTEST_RESULT"
export const SET_EXAM_RESULT = "SET_EXAM_RESULT"

export const SET_TEACHER_ONLINETEST_STUDENTANSWERS = "SET_TEACHER_ONLINETEST_STUDENTANSWERS"
export const ADMIN_TEACHER_HEADER = "ADMIN_TEACHER_HEADER"
export const SELECT_STUDENT = "SELECT_STUDENT"
export const ADMIN_FEE_HEADER = "ADMIN_FEE_HEADER"
export const ADMIN_TIMETABLE_HEADER = "ADMIN_TIMETABLE_HEADER"
export const GRADE_TYPE = "GRADE_TYPE"
export const SET_PARENT_STUDENT_LEAVE = "SET_PARENT_STUDENT_LEAVE"
