export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SET_FEE_INSTALLMENTS = "SET_FEE_INSTALLMENTS";
export const SET_YEAR = "SET_YEAR";
export const SET_FEE_TYPE = "SET_FEE_TYPE";
export const SET_CLASSES = "SET_CLASSES";
export const SET_DISTINCT_CLASSES = "SET_DISTINCT_CLASSES";
export const SET_CLASS_PERIOD = "SET_CLASS_PERIOD";
export const SET_SUBJECTS = "SET_SUBJECTS";
export const SET_TEACHERS = "SET_TEACHERS";
export const SET_TIMETABLE = "SET_TIMETABLE";
export const ASSIGNED_CLASS = "ASSIGNED_CLASS";
export const SET_CLASS_HOMEWORK = "SET_CLASS_HOMEWORK";
export const SET_PARENT_CHILDS = "SET_PARENT_CHILDS";
export const SET_PARENT_HOMEWORK = "SET_PARENT_HOMEWORK";
export const SET_CLASSWISE_TIMETABLE = "SET_CLASSWISE_TIMETABLE";
export const SET_EXAM_TYPE = "SET_EXAM_TYPE";

