export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const FILE_CREATED = "FILE_CREATED";
export const PARENT_CHILDREN = "PARENT_CHILDREN";
export const ASSIGNED_TEACHER_CLASS = "ASSIGNED_TEACHER_CLASS";
export const TEACHER_CLASS_ATTENDANCE = "TEACHER_CLASS_ATTENDANCE";
export const ADMIN_STUDENT_HEADER = "ADMIN_STUDENT_HEADER";
export const ADMIN_ATTENDANCE_HEADER = "ADMIN_ATTENDANCE_HEADER";